# Generated by Django 5.2.8 on 2025-11-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiPajak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objek_nama', models.CharField(max_length=100)),
                ('npwpd', models.CharField(max_length=20)),
                ('bulan', models.IntegerField()),
                ('tahun', models.IntegerField()),
                ('omzet_makanan', models.IntegerField()),
                ('omzet_minuman', models.IntegerField()),
                ('pajak', models.IntegerField()),
                ('status_bayar', models.BooleanField()),
                ('tgl_bayar', models.DateField()),
                ('tgl_jatuh_tempo', models.DateField()),
            ],
        ),
    ]
