# Generated by Django 5.2.8 on 2025-11-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_simtaxsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksipajak',
            name='bulan_huruf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='nopd',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='objek_alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='objek_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='pengguna_nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='subjenispajak_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='subjenispajak_nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='tgl_entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='tglbayar1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='transaksi_jmlhbayardenda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='transaksi_jmlhdendapembayaran',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='transaksi_kodebayarbank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='transaksi_kodeqris',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='transaksi_masaakhir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='transaksi_masaawal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='transaksi_periodepajak',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='transaksi_propertis',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='transaksi_tglakhirreklame',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='transaksi_tglawalreklame',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaksipajak',
            name='wp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaksipajak',
            name='bulan',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transaksipajak',
            name='npwpd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaksipajak',
            name='objek_nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaksipajak',
            name='omzet_makanan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaksipajak',
            name='omzet_minuman',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaksipajak',
            name='pajak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaksipajak',
            name='status_bayar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaksipajak',
            name='tahun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaksipajak',
            name='tgl_bayar',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaksipajak',
            name='tgl_jatuh_tempo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
